blank_issues_enabled: true
contact_links:
  - name: Bells Core Security Policy
    url: https://github.com/Nintondo/bellscoinV3/blob/main/SECURITY.md
    about: View security policy
  - name: Bellscoi Developers
    url: https://bellscoin.com
    about: Bellscoin homepage
